/*
Copyright (C) 2022 Paul "Buzz" Moschetti
    
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

package com.foo.web3.apps;

import com.foo.web3.providers.HttpFix;
import com.foo.web3.providers.Provider;

import com.foo.web3.generated.MyContract;

import java.math.BigInteger;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.web3j.crypto.Credentials;
import org.web3j.crypto.WalletUtils;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import org.web3j.protocol.http.HttpService;
import org.web3j.tx.Contract;  // for GAS_LIMIT constant
import org.web3j.tx.ManagedTransaction; // GAS_PRICE constant
import org.web3j.tx.Transfer;
import org.web3j.utils.Convert;
import org.web3j.utils.Numeric;


public class bsondeploy {

    private static final Logger log = LoggerFactory.getLogger(bsondeploy.class);

    public static void main(String[] args) throws Exception {
        new bsondeploy().run();
    }

    private void run() {

	HttpFix hf = null;

	try {
	    Provider pp = ProviderFactory.create(); // default!
	    hf = pp.vendHttpFix();
	    Web3j web3j = hf.getweb3j();
	    log.info("Connected to Ethereum client version: "
		     + web3j.web3ClientVersion().send().getWeb3ClientVersion());
	    Credentials credentials = pp.vendCredentials();

	    log.info("Credentials loaded");

	    //BigInteger gas_limit = Contract.GAS_LIMIT;
	    BigInteger gas_limit = BigInteger.valueOf(6_000_000);	    
	    log.info("Gas price,limit: " + pp.vendGasPrice() + ":" + gas_limit);
	    
	    log.info("Deploying smart contract");


	    MyContract contract = MyContract.deploy(
		    // Boilerplate args:
		    web3j, credentials, pp.vendGasPrice(), gas_limit,
		    // and now the args to MyContract constructor:
		          "CPTY1".getBytes(),
		          new BigInteger("7653")
				  ).send();

	    log.info("deploy.send() complete; get Contract address...");
	    
	    String contractAddress = contract.getContractAddress();

	    log.info("Contract address: " + contractAddress);
	    
	} catch(Exception e) {
	    System.out.println("epic fail: " + e);
		e.printStackTrace();
	}

	hf.shutdown();
    }
}
